elementary:
  outputs:
    default:
      type: "redshift"
      host: "redshift-cluster-1.cptkwmex8inn.us-east-1.redshift.amazonaws.com"
      port: 5439
      user: "awsuser"
      password: "Unnathigowda4"
      dbname: "dev"
      schema: "dbt_unnathi_redshift"
      threads: 4
